changelog:
  categories:
    - title: Features
      labels:
        - enhancement
    - title: Fixed
      labels:
        - bug
    - title: Refactors
      labels:
        - refactor
    - title: Packages/apps
      labels:
        - package::documentation
        - package::addition
        - package::breakage
    - title: Development
      labels:
        - ci
        - dependencies
    - title: Documentation
      labels:
        - documentation
